global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ligue-payments-api'
    static_configs:
      - targets: ['<EC2_PUBLIC_IP>:8080']
    metrics_path: '/metrics'
    # Substitua <EC2_PUBLIC_IP> pelo IP p√∫blico ou DNS do EC2
    # Ex: targets: ['54.123.45.67:8080'] ou ['api.ligue.com:8080']
